openapi: 3.0.3
info:
  title: CofeGB
  description: CofeGB app rest api specification
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /navMenu:
    get:
      description: Return app navigation menu entries
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/navMenuItem'
  /menu/{category}:
    get:
      description: Returns dish menu entries in a given category
      parameters:
        - name: category
          in: path
          description: Category of dish menu entries to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content: {}
        400:
          description: Invalid category supplied
          content: {}
components:
  schemas:
    navMenuItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Закуски
        route:
          type: string
          example: /menu
        icon:
          type: string
          example: starters
        query:
          type: string
          example: starters
        warn:
          type: boolean
          example: false
        warnMsg:
          type: string
          example: ""
